---
title: 'Data Science Internship: Week 3 & 4: The Last Stretch'
author: ~
date: '2018-07-17'
slug: data-science-internship-week-3-4-the-last-stretch
categories: [internship]
tags: [internship, reflection, advice]
---

# This Is It

I'm currently writting this on the last week of the internship and oh what an experience it has been. Rather than a technical post I'll just write about things that I've learned through the process and things I found interesting. 

## What have I learned?

- Sometimes you will hit a wall while coding and it will seem like there's no way to improve a model. But accuracy isn't everything. We added more data to our training data set in order to have a wider range of learning rather than a higher accuracy with a specific set for data. Adding images that lowered the accuracy might have made us sad but in reality, it will help our model recognize a wider range of images. 

- You have to come up with your own ideas. As an intern we sometimes expect to be handed everything we need to do in a tidy to do list and just check off the ticks. But sometimes our supervisors can be cool enough to give us the reigns for certain things. It was cool to have the chance to brainstorm ideas to improve our model and try them (they didn't work that well but it got us to think out of the box).

- Communication. This is a big one, I'm not very good a communicating my ideas and working in a team definitely helped me to organize my thoughts first and then try my hardest to eloquently try to make some sense. Not only reporting to a supervisor but actually working with someone side by side writing code together was an awesome experience (if you get the right someone of course, which I did (thank God)).

- It's okay to ask questions! Supervisors don't expect you to know everything about convolutional neural networks, or whatever kind of models off the bat. And most of them are willing to sit down with you and try to explain how things work (even though we all know all models are literally magic, and that's how they work).

## What did I enjoy the most?

- I enjoyed having some free time here and there to go on websites like Data Camp or read articles about what I'm working with. 

- I enjoyed having lunch with my co workers. 

- I enjoyed working on something I'm really passionate about and hopefully do this for the rest of my professional career. 
