---
title: 'Data Science Internship: Week 2 - The Uh''s and Ah''s'
author: 'Stacy Kam'
date: '2018-07-02'
slug: data-science-internship-week-2-the-uh-s-and-ah-srmd
categories: [internship, Python]
tags: [tensorflow, tensors]
---

# So How Are Things Going?

Week 2 has been more of an uphill battle than the feeling of discovering new things and excitement from last week. I feel this is how work is supposed to be like, hopefully we'll get out of this slump. 

## What Slump?

We try to keep making improvements to our model but it's kind of regressing. We made good progress last week but everytime we try to improve it it gets worse. 

## What Exactly is Tensorflow Tho?

I have been using Tensorflow as a backend for my Keras model but lately while debugging I would constantly run into the issue of not being able to print out objects because they were Tensors! So Tensorflow basically takes care of all the details and mind boggling algortihms that happen during machine learning, they take care of connecting all the inputs and outputs between layers; look at it as nodes comprised of calculations and edges connecting those nodes, these edges are the tensors. 

I found this helpful [article](https://www.aiworkbox.com/lessons/print-the-value-of-a-tensor-object-in-tensorflow) on how to print tensors when debugging.
 
## Update on Becoming a VIM God

Well, we are working on an ssh instance to speed up the training process (from 145ish to 80ish seconds per epoch!) so I've been having to use vim to edit the code and run it right away. I found this pretty nifty [cheat sheet](https://vim.rtorr.com) to look like a pro lol. 